First pass at updates and deploy from GitHub
hyphacoop/hypha.coop-archived pull request #1
Opened 2019-06-11 18:01 UTC by patcon

This PR does a few things:

- [x] converts static html template to simple jekyll one
- [x] replaced heavy background video with blurred screenshot
- [x] adds contact details
- [x] adds our org name to template
- [x] add temp placeholder logo
- [x] adds our linkedin and social links (only twitter & linkedin activated for now)
- [x] adds deploy script to deploy on our server with each commit to master

![Screen Shot 2019-06-11 at 1 22 27 PM](https://user-images.githubusercontent.com/305339/59292920-04f3cb00-8c4c-11e9-812a-7889d5ae6783.png)

Still to do:

- [ ] test/fix deploy script (awaiting unblock [help](https://matrix.to/#/!JloFJtoONurMdgcZCa:tomesh.net/$15602728261114FMLHr:tomesh.net?via=tomesh.net&via=aseriesoftubez.com) from @ASoTNetworks)
- [ ] replace boilerplate readme with our docs
- [ ] add temporary physical address (optional)
- [ ] make our first tweet (optional)

2019-07-04 17:08 UTC, patcon commented
In the interest of simplicity, let's forget the tweet, and forget the docs. I suggest we do the latter in a separate PR :)

2019-07-04 17:11 UTC, patcon commented on .travis.yml
> +  - if [ "$TRAVIS_SECURE_ENV_VARS" == true ]; then openssl aes-256-cbc -K $encrypted_3a24d53b15ee_key -iv $encrypted_3a24d53b15ee_iv -in scripts/id_rsa.enc -out scripts/id_rsa -d
```suggestion
  - if [ "$TRAVIS_SECURE_ENV_VARS" == true ]; then openssl aes-256-cbc -K $encrypted_3a24d53b15ee_key -iv $encrypted_3a24d53b15ee_iv -in scripts/id_rsa.enc -out scripts/id_rsa -d; fi
```

2019-07-16 19:38 UTC, dcwalk commented
@patcon do you need a review on this? Not sure on status!

2019-07-24 05:39 UTC, patcon commented
Yes please! Wasn't sure whose domain this would be, so have just solicited in chat a few times

2019-08-07 20:28 UTC, patcon commented
@dcwalk you have an insight on this travis failure? I thought I was done and ready for review, but I'm stumbling on this general error...

2019-08-09 13:03 UTC, dcwalk commented on .travis.yml
> +      - patrick.c.connolly@gmail.com
will want to update this

2019-08-09 13:09 UTC, dcwalk commented
It says "No Rakefile found (looking for: rakefile, Rakefile, rakefile.rb, Rakefile.rb)"

I think the deploy process could be done all with Travis CI and I'm not entirely sure why you are raking at all :woman_shrugging: 

Could you explain your flow of deploy somewhere? (In a readme?) That would help me understand the what/why better.

2019-08-09 23:55 UTC, patcon commented
> I'm not entirely sure why you are raking tbh

I'm not! It's seemingly a travis default. Seeing that ournetworks.ca repo gets rake via html-proofer, so I'll just try to copy as much as i can from there 🤞 

> Could you explain your flow of deploy somewhere? (In a readme?) That would help me understand the what/why better.

Copied scripts from ournetwork, with tweaks for setting port in deploy.sh. will copy from there or write new :) thanks for sanity check

2019-08-10 00:45 UTC, patcon commented
Ok, working now. Good for reviews and merge if looks alright.

(Scaffold is all from ournetworks.ca repo, except for top of README and deploy.sh)

2019-08-12 06:04 UTC, benhylau requested changes
Why don't we literally take the .travis.yml from https://github.com/ournetworks/ournetworks.ca/blob/master/.travis.yml then we can push the site to dat too for free

2019-08-12 06:04 UTC, benhylau commented on .travis.yml
> +  script: bash scripts/deploy.sh patrick scripts/id_rsa webserv.hypha.coop 10025
`s/patrick/travis`

2019-08-12 06:34 UTC, patcon commented on .travis.yml
> +  script: bash scripts/deploy.sh patrick scripts/id_rsa webserv.hypha.coop 10025
@ASoTNetworks will need to create a new user on the server, I think :)

Could you walk me through doing that elon?

2019-08-12 06:36 UTC, patcon commented
I'm down for that ben..! New PR or this one? (Not sure if it's as simple as just copying Travis config, or if there's more to it

2019-08-12 06:42 UTC, patcon commented on .travis.yml
> +      - patrick.c.connolly@gmail.com
To our m******@hypha.coop, or something else? Maybe devops@hypha.coop for tech stuff like this?(could always alias it to m******@ for now anyhow). Thoughts @ASoTNetworks @YurkoWasHere ?

2019-08-12 06:46 UTC, patcon commented on .travis.yml
> +      - patrick.c.connolly@gmail.com
```suggestion
      - members@hypha.coop
```

2019-08-12 07:26 UTC, benhylau commented
I don't mean to scope creep but saw this is based on OurNetworks so was wondering if it's valuable to keep the two mostly in sync.

2019-08-12 08:12 UTC, patcon commented
Seems we might want to allude/link to DAT in visible bits of page, so re-ticketed that part. Added todo for your deploy suggestion

2019-08-12 22:43 UTC, benhylau commented
Good to merge after we make Travis user then!

2019-08-13 00:06 UTC, dcwalk commented on .travis.yml
> +  - gem install bundler
so looks like this resolved the issue?

2019-08-13 00:06 UTC, dcwalk commented
Agree about re-ticketing Dat, it isn't just the travis config file that has to be set up

2019-08-13 01:22 UTC, ASoTNetworks commented on .travis.yml
> +      - patrick.c.connolly@gmail.com
I think members@hypha.coop would work

2019-08-13 04:13 UTC, patcon commented
> good to merge after we make Travis / deploy-bot user then! 

Good call. "deploy" user was common in Capistrano days. No need to tie it to Travis in a way that might rot.

2019-08-13 11:39 UTC, YurkoWasHere commented on .travis.yml
> +      - patrick.c.connolly@gmail.com
I think members may get a little to chatty as we load more and more of this stuff onto the email. I was thinking even for services like Instagram and such.

It may be worth looking at spinning off emails for individual workgroups maybe? or just a devops one like you suggested.

2019-08-30 18:34 UTC, patcon commented on .travis.yml
> +      - patrick.c.connolly@gmail.com
pending [chat context](https://matrix.to/#/!wvFLvXHaNrxWWwFOKj:tomesh.net/$15671898426390vkjVF:tomesh.net?via=tomesh.net&via=matrix.org&via=elon.li)
```suggestion
      - infra@hypha.coop
```

2019-08-30 19:38 UTC, patcon commented on .travis.yml
> +  script: bash scripts/deploy.sh patrick scripts/id_rsa webserv.hypha.coop 10025
```suggestion
  script: bash scripts/deploy.sh deploy scripts/id_rsa webserv.hypha.coop 10025
```

2019-08-30 19:42 UTC, patcon commented
K, this is ready for final review.

- created infra@hypha.coop alias
- create `deploy` user on server

2019-08-30 22:32 UTC, merged

2019-08-31 01:37 UTC, patcon commented
k permissions fixed and deploying fine: https://travis-ci.org/hyphacoop/hypha.coop/builds/579029611

2020-04-03 01:08 UTC, dcwalk commented
Udit flagged the concern, which I agree with -- that this moves all our contact info to the bottom of the page. That seems like a bad pattern: no link to social or email until you've scrolled to the bottom